<?php

/**
 * @file
 * Primary module hooks for Event Registration module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function event_registration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.event_registration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Event Registration module allows users to register for events.') . '</p>';
      return $output;
  }
}
